import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";
import CartSidebar from "@/components/models/CartSidebar";
import LayoutContent from "@/components/LayoutContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  fallback: [
    "miui",
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    ".SFNSText-Regular",
    "Helvetica",
    "Arial",
    "sans-serif",
    "serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Noto Color Emoji",
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dressfair",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CartProvider>
            <LayoutContent>{children}</LayoutContent>
            <CartSidebar />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
